# Generated by Django 5.1.1 on 2024-09-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raterapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameimage",
            name="image",
        ),
        migrations.AddField(
            model_name="gameimage",
            name="action_pic",
            field=models.ImageField(null=True, upload_to="actionimages"),
        ),
        migrations.AlterField(
            model_name="gameimage",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="raterapi.game",
            ),
        ),
    ]
